on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    container:
      image: williamyeh/ansible:alpine3-onbuild
      env:
        TEST_ENV: ENV_VAL
      volumes:
        - ./:/tmp
    steps:
      - name: Test action 1
        runs: ls -lR /tmp

    # - name: Hello world action step
    #   id: hello
    #   uses: swagcurity/ansible-action@master
    #   with:
    #     entrypoint: /bin/echo
    #     args: The ${{ github.event_name }} event triggered this step.
    #     who-to-greet: 'Mona the Octocat'
    # # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
