name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to the registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p'${{ secrets.DOCKER_PASSWORD }}'
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ansible
    - name: retrieve ansible version
      run: docker run -t ansible ansible --version
